"""Write the compiled LangGraph as Mermaid to docs/graph.md."""

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "backend"))

from app.graph.builder import build_graph  # noqa: E402

mermaid = build_graph().get_graph().draw_mermaid()
(ROOT / "docs" / "graph.md").write_text(
    "# ChurnLens analysis graph\n\n"
    "Generated by `scripts/export_graph.py` from `backend/app/graph/builder.py`.\n"
    "Dotted edges are conditional.\n\n"
    f"```mermaid\n{mermaid}```\n",
    encoding="utf-8",
)
print("wrote docs/graph.md")
