/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/analyze/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze */
        post: operations["analyze_analyze__session_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/confirm-schema/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Schema */
        post: operations["confirm_schema_confirm_schema__session_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/predictions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Predictions */
        get: operations["predictions_predictions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/predictions/{session_id}/csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Predictions Csv */
        get: operations["predictions_csv_predictions__session_id__csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/results/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Results */
        get: operations["results_results__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sample": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Load Sample */
        post: operations["load_sample_sample_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stream/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream */
        get: operations["stream_stream__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload */
        post: operations["upload_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/upload/{session_id}/sheet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Choose Sheet */
        post: operations["choose_sheet_upload__session_id__sheet_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Assumption */
        Assumption: {
            /** Detail */
            detail: string;
            /** Name */
            name: string;
            /** Result */
            result: boolean;
        };
        /** AwaitingConfirmationEvent */
        AwaitingConfirmationEvent: {
            proposal?: components["schemas"]["SchemaProposalOut"] | null;
        };
        /** Body_choose_sheet_upload__session_id__sheet_post */
        Body_choose_sheet_upload__session_id__sheet_post: {
            /** Sheet Name */
            sheet_name: string;
        };
        /** Body_upload_upload_post */
        Body_upload_upload_post: {
            /** File */
            file: string;
            /** Sheet Name */
            sheet_name?: string | null;
        };
        /** CalculationStep */
        CalculationStep: {
            /** Formula */
            formula: string;
            /** Label */
            label: string;
            /** Substituted */
            substituted: string;
        };
        /** ClassBalance */
        ClassBalance: {
            /** Negative */
            negative: number;
            /** Positive */
            positive: number;
            /** Positive Label */
            positive_label: string;
            /** Positive Rate */
            positive_rate: number;
        };
        /** CleaningStep */
        CleaningStep: {
            /** Column */
            column?: string | null;
            /** Detail */
            detail: string;
            /** Rows Affected */
            rows_affected: number;
            /** Step */
            step: string;
        };
        /** ConfirmedColumn */
        ConfirmedColumn: {
            /** Name */
            name: string;
            /**
             * Semantic Type
             * @enum {string}
             */
            semantic_type: "id" | "numeric" | "categorical" | "binary" | "datetime" | "text";
        };
        /** ConfirmedSchema */
        ConfirmedSchema: {
            /** Columns */
            columns?: components["schemas"]["ConfirmedColumn"][];
            /** Id Columns */
            id_columns?: string[];
            /** Positive Label */
            positive_label: string;
            /** Revenue Column */
            revenue_column?: string | null;
            /** Target Column */
            target_column: string;
            /** Time Column */
            time_column?: string | null;
        };
        /** ConfusionMatrix */
        ConfusionMatrix: {
            /** Fn */
            fn: number;
            /** Fp */
            fp: number;
            /** Tn */
            tn: number;
            /** Tp */
            tp: number;
        };
        /** CvScores */
        CvScores: {
            /** Name */
            name: string;
            /** Pr Auc Mean */
            pr_auc_mean?: number | null;
            /** Pr Auc Std */
            pr_auc_std?: number | null;
            /** Roc Auc Mean */
            roc_auc_mean?: number | null;
            /** Roc Auc Std */
            roc_auc_std?: number | null;
        } & {
            [key: string]: unknown;
        };
        /** DataHealth */
        DataHealth: {
            class_balance: components["schemas"]["ClassBalance"];
            /** Columns */
            columns: number;
            /** Duplicates Removed */
            duplicates_removed: number;
            /** Health Score */
            health_score: number;
            /** Missing Pct After */
            missing_pct_after: {
                [key: string]: number;
            };
            /** Missing Pct Before */
            missing_pct_before: {
                [key: string]: number;
            };
            /** Outliers Flagged */
            outliers_flagged: {
                [key: string]: components["schemas"]["OutlierCounts"];
            };
            /** Rows After */
            rows_after: number;
            /** Rows Before */
            rows_before: number;
            /** Score Formula */
            score_formula: string;
        };
        /** DoneEvent */
        DoneEvent: {
            /** Final Error */
            final_error?: string | null;
            /** Ok */
            ok: boolean;
        };
        /** DriverImpactRow */
        DriverImpactRow: {
            /** Feature */
            feature: string;
            /** Mean Abs Shap */
            mean_abs_shap?: number | null;
            /** Odds Ratio */
            odds_ratio?: number | null;
            /** Or Ci Lower */
            or_ci_lower?: number | null;
            /** Or Ci Upper */
            or_ci_upper?: number | null;
            /** Or Label */
            or_label?: string | null;
            /** P Adjusted */
            p_adjusted?: number | null;
            /** Permutation Importance */
            permutation_importance?: number | null;
            /** Permutation Rank */
            permutation_rank?: number | null;
            /** Significant */
            significant?: boolean | null;
            /** Test Name */
            test_name?: string | null;
        };
        /** DroppedTerm */
        DroppedTerm: {
            /** Reason */
            reason: string;
            /** Term */
            term: string;
        };
        /** EffectSize */
        EffectSize: {
            /** Band */
            band: string;
            /** Name */
            name: string;
            /** Value */
            value?: number | null;
        };
        /** ErrorEvent */
        ErrorEvent: {
            /**
             * Fatal
             * @default false
             */
            fatal: boolean;
            /** Message */
            message: string;
            /** Node */
            node?: string | null;
        };
        /** FeatureImportance */
        FeatureImportance: {
            /** Driver Impact */
            driver_impact?: components["schemas"]["DriverImpactRow"][];
            /** Features */
            features?: components["schemas"]["PermutationItem"][];
            /** Method */
            method?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** Figure */
        Figure: {
            /** Display */
            display: string;
            /** Source Key */
            source_key: string;
            /** Value */
            value: number;
        };
        /** GroupStats */
        GroupStats: {
            /** Mean */
            mean?: number | null;
            /** Median */
            median?: number | null;
            /** N */
            n: number;
            /** Sd */
            sd?: number | null;
        } & {
            [key: string]: unknown;
        };
        /** HTTPErrorOut */
        HTTPErrorOut: {
            /** Detail */
            detail: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HeldOutMetrics */
        HeldOutMetrics: {
            /** Accuracy */
            accuracy?: number | null;
            confusion_matrix?: components["schemas"]["ConfusionMatrix"] | null;
            /** F1 */
            f1?: number | null;
            /** N Test */
            n_test: number;
            /** Pr Auc */
            pr_auc?: number | null;
            /** Precision */
            precision?: number | null;
            /** Recall */
            recall?: number | null;
            /** Roc Auc */
            roc_auc?: number | null;
            roc_curve?: components["schemas"]["RocCurve"] | null;
            /** Threshold */
            threshold?: number | null;
        } & {
            [key: string]: unknown;
        };
        /** HypothesisInputs */
        HypothesisInputs: {
            cell_contributions?: components["schemas"]["LabelledTable"] | null;
            /** Churn Rate By Level */
            churn_rate_by_level?: {
                [key: string]: number;
            } | null;
            expected?: components["schemas"]["LabelledTable"] | null;
            /** Groups */
            groups?: {
                [key: string]: components["schemas"]["GroupStats"];
            } | null;
            /** N */
            n?: number | null;
            observed?: components["schemas"]["LabelledTable"] | null;
        } & {
            [key: string]: unknown;
        };
        /** HypothesisResults */
        HypothesisResults: {
            /** Alpha */
            alpha: number;
            /** Correction */
            correction: string;
            /** N Significant */
            n_significant: number;
            /** N Tests */
            n_tests: number;
            /** Skipped */
            skipped?: components["schemas"]["SkippedTest"][];
            /** Tests */
            tests?: components["schemas"]["HypothesisTest"][];
        } & {
            [key: string]: unknown;
        };
        /** HypothesisTest */
        HypothesisTest: {
            /** Assumptions */
            assumptions?: components["schemas"]["Assumption"][];
            /** Conclusion */
            conclusion: string;
            /** Df */
            df?: number | null;
            effect_size: components["schemas"]["EffectSize"];
            /** H0 */
            h0: string;
            /** H1 */
            h1: string;
            inputs: components["schemas"]["HypothesisInputs"];
            /**
             * Kind
             * @enum {string}
             */
            kind: "categorical" | "numeric";
            /** Merged Levels */
            merged_levels?: string[];
            /** P Adjusted */
            p_adjusted?: number | null;
            /** P Value */
            p_value?: number | null;
            /** Significant */
            significant: boolean;
            /** Statistic */
            statistic?: number | null;
            /** Statistic Name */
            statistic_name: string;
            /** Steps */
            steps?: components["schemas"]["CalculationStep"][];
            /** Test Name */
            test_name: string;
            /** Variable */
            variable: string;
            /** Why */
            why: string;
        } & {
            [key: string]: unknown;
        };
        /** Impact */
        Impact: {
            /** Assumption */
            assumption: string;
            /** Source Key */
            source_key: string;
            /** Value */
            value: number;
        };
        /** ImpactEstimates */
        ImpactEstimates: {
            overall: components["schemas"]["ImpactGroup"];
            /** Revenue Column */
            revenue_column?: string | null;
            /** Revenue Note */
            revenue_note?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** ImpactGroup */
        ImpactGroup: {
            /** Churn Rate */
            churn_rate: number;
            /** Churners */
            churners: number;
            /** Customers */
            customers: number;
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Monthly Revenue At Risk */
            monthly_revenue_at_risk?: number | null;
        } & {
            [key: string]: unknown;
        };
        /** Insight */
        Insight: {
            /**
             * Causality Note
             * @default
             */
            causality_note: string;
            /** Figures */
            figures?: components["schemas"]["Figure"][];
            /** Id */
            id: string;
            /** Significant */
            significant: boolean;
            /** Text */
            text: string;
            /** Title */
            title: string;
        };
        /** LabelOption */
        LabelOption: {
            /** Column */
            column: string;
            /** Values */
            values: string[];
        };
        /** LabelledTable */
        LabelledTable: {
            /** Columns */
            columns: string[];
            /** Rows */
            rows: string[];
            /** Values */
            values: number[][];
        };
        /** LeakageWarning */
        LeakageWarning: {
            /** Column */
            column: string;
            /** Measure */
            measure: string;
            /** Value */
            value: number;
        };
        /** ModelMetrics */
        ModelMetrics: {
            /** Chosen Model */
            chosen_model: string;
            /** Chosen Model Name */
            chosen_model_name: string;
            /** Cv */
            cv?: {
                [key: string]: components["schemas"]["CvScores"];
            };
            /** Leakage Warnings */
            leakage_warnings?: components["schemas"]["LeakageWarning"][];
            /** N Test */
            n_test: number;
            /** N Train */
            n_train: number;
            risk_bands?: components["schemas"]["RiskBands"] | null;
            /** Selection Rule */
            selection_rule?: string | null;
            test: components["schemas"]["HeldOutMetrics"];
        } & {
            [key: string]: unknown;
        };
        /** NodeFinishEvent */
        NodeFinishEvent: {
            /** Detail */
            detail?: string | null;
            /** Node */
            node: string;
            /**
             * Status
             * @enum {string}
             */
            status: "started" | "done" | "skipped" | "failed";
        };
        /** NodeStartEvent */
        NodeStartEvent: {
            /** Node */
            node: string;
        };
        /** OddsRatioTerm */
        OddsRatioTerm: {
            /** Ci Lower */
            ci_lower?: number | null;
            /** Ci Upper */
            ci_upper?: number | null;
            /** Feature */
            feature: string;
            /** Kind */
            kind: string;
            /** Label */
            label: string;
            /** Level */
            level?: string | null;
            /** Odds Ratio */
            odds_ratio?: number | null;
            /** P Value */
            p_value?: number | null;
            /** Reference */
            reference?: string | null;
            /** Term */
            term: string;
        } & {
            [key: string]: unknown;
        };
        /** OddsRatios */
        OddsRatios: {
            /** Converged */
            converged?: boolean | null;
            /** Dropped */
            dropped?: components["schemas"]["DroppedTerm"][];
            /** Error */
            error?: string | null;
            /** Method */
            method?: string | null;
            /** N */
            n?: number | null;
            /** Pseudo R2 */
            pseudo_r2?: number | null;
            /** Terms */
            terms?: components["schemas"]["OddsRatioTerm"][];
        } & {
            [key: string]: unknown;
        };
        /** OutlierCounts */
        OutlierCounts: {
            /** Iqr */
            iqr: number;
            /** Zscore */
            zscore: number;
        };
        /** PermutationItem */
        PermutationItem: {
            /** Feature */
            feature: string;
            /** Importance Mean */
            importance_mean: number;
            /** Importance Std */
            importance_std: number;
            /** Rank */
            rank: number;
        };
        /** PredictionRow */
        PredictionRow: {
            /** Actual Churn */
            actual_churn: number;
            /** Churn Probability */
            churn_probability: number;
            /** Customer Id */
            customer_id: string;
            /** Reason 1 */
            reason_1?: string | null;
            /** Reason 2 */
            reason_2?: string | null;
            /** Reason 3 */
            reason_3?: string | null;
            /**
             * Risk Band
             * @enum {string}
             */
            risk_band: "High" | "Medium" | "Low";
        };
        /** PredictionsPage */
        PredictionsPage: {
            /** Available */
            available: boolean;
            /** Band */
            band?: ("High" | "Medium" | "Low") | null;
            /** Items */
            items: {
                [key: string]: unknown;
            }[];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Pages */
            pages: number;
            /** Total */
            total: number;
        };
        /** PredictionsResponse */
        PredictionsResponse: {
            /** Band */
            band?: ("High" | "Medium" | "Low") | null;
            /** Items */
            items: components["schemas"]["PredictionRow"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Pages */
            pages: number;
            /** Q */
            q?: string | null;
            /** Total */
            total: number;
        };
        /** ProposedColumn */
        ProposedColumn: {
            /** Confidence */
            confidence: number;
            /** Name */
            name: string;
            /**
             * Semantic Type
             * @enum {string}
             */
            semantic_type: "id" | "numeric" | "categorical" | "binary" | "datetime" | "text";
        };
        /** Recommendation */
        Recommendation: {
            /** Action */
            action: string;
            customers_affected: components["schemas"]["Figure"];
            /**
             * Effort
             * @enum {string}
             */
            effort: "low" | "medium" | "high";
            /** Figures */
            figures?: components["schemas"]["Figure"][];
            /**
             * Group
             * @enum {string}
             */
            group: "quick_win" | "medium_term" | "strategic";
            /** Id */
            id: string;
            impact: components["schemas"]["Impact"];
            /** Priority */
            priority: number;
            /** Problem */
            problem: string;
            /** Target Segment */
            target_segment: string;
        };
        /**
         * ResultsPayload
         * @description Keys the dashboard reads are typed; the rest pass through until their tab is built.
         */
        ResultsPayload: {
            /** Cleaning Log */
            cleaning_log?: components["schemas"]["CleaningStep"][] | null;
            data_health?: components["schemas"]["DataHealth"] | null;
            /** Errors */
            errors?: components["schemas"]["ErrorEvent"][];
            feature_importance?: components["schemas"]["FeatureImportance"] | null;
            /** Final Error */
            final_error?: string | null;
            /** Final Insights */
            final_insights?: components["schemas"]["Insight"][] | null;
            /** Final Recommendations */
            final_recommendations?: components["schemas"]["Recommendation"][] | null;
            hypothesis_results?: components["schemas"]["HypothesisResults"] | null;
            impact_estimates?: components["schemas"]["ImpactEstimates"] | null;
            model_metrics?: components["schemas"]["ModelMetrics"] | null;
            odds_ratios?: components["schemas"]["OddsRatios"] | null;
            /** Positive Label */
            positive_label?: string | null;
            shap_summary?: components["schemas"]["ShapSummary"] | null;
            /** Target Column */
            target_column?: string | null;
            validation_report?: components["schemas"]["ValidationReport"] | null;
        } & {
            [key: string]: unknown;
        };
        /** ResultsResponse */
        ResultsResponse: {
            predictions: components["schemas"]["PredictionsPage"];
            results: components["schemas"]["ResultsPayload"];
            /** Session Id */
            session_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "awaiting_confirmation" | "done" | "failed" | "interrupted";
        };
        /** RiskBands */
        RiskBands: {
            /** Band Counts */
            band_counts: {
                [key: string]: number;
            };
            /** Thresholds */
            thresholds: {
                [key: string]: number;
            };
            /** Total */
            total: number;
        } & {
            [key: string]: unknown;
        };
        /** RocCurve */
        RocCurve: {
            /** Fpr */
            fpr: number[];
            /** Tpr */
            tpr: number[];
        };
        /** RunStatusResponse */
        RunStatusResponse: {
            /** Session Id */
            session_id: string;
            /** Status */
            status: string;
        };
        /** SchemaProblems */
        SchemaProblems: {
            /** Message */
            message: string;
            /** Problems */
            problems: string[];
        };
        /**
         * SchemaProblemsOut
         * @description Body of a 422 from POST /confirm-schema when the schema does not fit the data.
         */
        SchemaProblemsOut: {
            detail: components["schemas"]["SchemaProblems"];
        };
        /** SchemaProposalOut */
        SchemaProposalOut: {
            /** Columns */
            columns: components["schemas"]["ProposedColumn"][];
            /** Id Columns */
            id_columns?: string[];
            /** Label Options */
            label_options?: components["schemas"]["LabelOption"][];
            /** Positive Label */
            positive_label?: string | null;
            /**
             * Reasoning
             * @default
             */
            reasoning: string;
            /** Revenue Column */
            revenue_column?: string | null;
            /**
             * Source
             * @enum {string}
             */
            source: "ai+rules" | "rules";
            /** Target Candidates */
            target_candidates?: string[];
            /** Target Column */
            target_column?: string | null;
            /** Time Column */
            time_column?: string | null;
        };
        /** ShapFeature */
        ShapFeature: {
            /** Feature */
            feature: string;
            /** Kind */
            kind: string;
            /** Points */
            points: components["schemas"]["ShapPoint"][];
        };
        /** ShapGlobal */
        ShapGlobal: {
            /** Feature */
            feature: string;
            /** Mean Abs Shap */
            mean_abs_shap: number;
        };
        /** ShapPoint */
        ShapPoint: {
            /** Shap */
            shap: number;
            /** Value */
            value?: number | string | null;
        };
        /** ShapSummary */
        ShapSummary: {
            /** Beeswarm */
            beeswarm?: components["schemas"]["ShapFeature"][];
            /** Error */
            error?: string | null;
            /** Explained Model */
            explained_model?: string | null;
            /** Global */
            global?: components["schemas"]["ShapGlobal"][];
            /** Method */
            method?: string | null;
            /** N Rows */
            n_rows?: number | null;
            /** Scale */
            scale?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** SkippedTest */
        SkippedTest: {
            /** Reason */
            reason: string;
            /** Variable */
            variable: string;
        };
        /**
         * StreamEvents
         * @description Documentation only: the payload type of each SSE event name.
         */
        StreamEvents: {
            awaiting_confirmation: components["schemas"]["AwaitingConfirmationEvent"];
            done: components["schemas"]["DoneEvent"];
            error: components["schemas"]["ErrorEvent"];
            /** Heartbeat */
            heartbeat: {
                [key: string]: unknown;
            };
            node_finish: components["schemas"]["NodeFinishEvent"];
            node_start: components["schemas"]["NodeStartEvent"];
            /** Resumed */
            resumed: {
                [key: string]: unknown;
            };
        };
        /** UploadResponse */
        UploadResponse: {
            /**
             * Columns
             * @default []
             */
            columns: string[];
            /** Filename */
            filename: string;
            /** Rows */
            rows?: number | null;
            /** Session Id */
            session_id: string;
            /** Sheet Name */
            sheet_name?: string | null;
            /**
             * Sheets
             * @default []
             */
            sheets: string[];
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "choose_sheet";
            /**
             * Warnings
             * @default []
             */
            warnings: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** ValidationReport */
        ValidationReport: {
            /** Checked */
            checked: number;
            /** Dropped */
            dropped: number;
            /** Failed */
            failed: number;
            /** Final */
            final: boolean;
            /** Passed */
            passed: number;
        } & {
            [key: string]: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    analyze_analyze__session_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStatusResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPErrorOut"];
                };
            };
            /** @description Gone */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_schema_confirm_schema__session_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmedSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStatusResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPErrorOut"];
                };
            };
            /** @description Gone */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPErrorOut"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchemaProblemsOut"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    predictions_predictions__session_id__get: {
        parameters: {
            query?: {
                page?: number;
                band?: ("High" | "Medium" | "Low") | null;
                /** @description Case-insensitive part of a customer ID */
                q?: string | null;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictionsResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPErrorOut"];
                };
            };
            /** @description Gone */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    predictions_csv_predictions__session_id__csv_get: {
        parameters: {
            query?: {
                band?: ("High" | "Medium" | "Low") | null;
                /** @description Case-insensitive part of a customer ID */
                q?: string | null;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Filtered predictions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": unknown;
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPErrorOut"];
                };
            };
            /** @description Gone */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    results_results__session_id__get: {
        parameters: {
            query?: {
                page?: number;
                band?: ("High" | "Medium" | "Low") | null;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultsResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPErrorOut"];
                };
            };
            /** @description Gone */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    load_sample_sample_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPErrorOut"];
                };
            };
            /** @description Gone */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPErrorOut"];
                };
            };
            /** @description Content Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPErrorOut"];
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPErrorOut"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPErrorOut"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPErrorOut"];
                };
            };
        };
    };
    stream_stream__session_id__get: {
        parameters: {
            query?: {
                /** @description Resume after this event id. For clients that cannot send Last-Event-ID, such as a browser EventSource re-created after it closed. */
                after?: number | null;
            };
            header?: {
                "Last-Event-ID"?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server-sent events; StreamEvents maps each event name to its data payload. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamEvents"];
                    "text/event-stream": unknown;
                };
            };
            /** @description Gone */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPErrorOut"];
                };
            };
            /** @description Gone */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPErrorOut"];
                };
            };
            /** @description Content Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPErrorOut"];
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPErrorOut"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPErrorOut"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPErrorOut"];
                };
            };
        };
    };
    choose_sheet_upload__session_id__sheet_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_choose_sheet_upload__session_id__sheet_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPErrorOut"];
                };
            };
            /** @description Gone */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPErrorOut"];
                };
            };
            /** @description Content Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPErrorOut"];
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPErrorOut"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPErrorOut"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPErrorOut"];
                };
            };
        };
    };
}
