/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/analyze/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze */
        post: operations["analyze_analyze__session_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/confirm-schema/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Schema */
        post: operations["confirm_schema_confirm_schema__session_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/results/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Results */
        get: operations["results_results__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sample": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Load Sample */
        post: operations["load_sample_sample_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stream/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream */
        get: operations["stream_stream__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload */
        post: operations["upload_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/upload/{session_id}/sheet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Choose Sheet */
        post: operations["choose_sheet_upload__session_id__sheet_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AwaitingConfirmationEvent */
        AwaitingConfirmationEvent: {
            proposal?: components["schemas"]["SchemaProposalOut"] | null;
        };
        /** Body_choose_sheet_upload__session_id__sheet_post */
        Body_choose_sheet_upload__session_id__sheet_post: {
            /** Sheet Name */
            sheet_name: string;
        };
        /** Body_upload_upload_post */
        Body_upload_upload_post: {
            /** File */
            file: string;
            /** Sheet Name */
            sheet_name?: string | null;
        };
        /** ConfirmedColumn */
        ConfirmedColumn: {
            /** Name */
            name: string;
            /**
             * Semantic Type
             * @enum {string}
             */
            semantic_type: "id" | "numeric" | "categorical" | "binary" | "datetime" | "text";
        };
        /** ConfirmedSchema */
        ConfirmedSchema: {
            /** Columns */
            columns?: components["schemas"]["ConfirmedColumn"][];
            /** Id Columns */
            id_columns?: string[];
            /** Positive Label */
            positive_label: string;
            /** Revenue Column */
            revenue_column?: string | null;
            /** Target Column */
            target_column: string;
            /** Time Column */
            time_column?: string | null;
        };
        /** DoneEvent */
        DoneEvent: {
            /** Final Error */
            final_error?: string | null;
            /** Ok */
            ok: boolean;
        };
        /** ErrorEvent */
        ErrorEvent: {
            /**
             * Fatal
             * @default false
             */
            fatal: boolean;
            /** Message */
            message: string;
            /** Node */
            node?: string | null;
        };
        /** HTTPErrorOut */
        HTTPErrorOut: {
            /** Detail */
            detail: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** NodeFinishEvent */
        NodeFinishEvent: {
            /** Detail */
            detail?: string | null;
            /** Node */
            node: string;
            /**
             * Status
             * @enum {string}
             */
            status: "started" | "done" | "skipped" | "failed";
        };
        /** NodeStartEvent */
        NodeStartEvent: {
            /** Node */
            node: string;
        };
        /** PredictionsPage */
        PredictionsPage: {
            /** Available */
            available: boolean;
            /** Band */
            band?: ("High" | "Medium" | "Low") | null;
            /** Items */
            items: {
                [key: string]: unknown;
            }[];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Pages */
            pages: number;
            /** Total */
            total: number;
        };
        /** ProposedColumn */
        ProposedColumn: {
            /** Confidence */
            confidence: number;
            /** Name */
            name: string;
            /**
             * Semantic Type
             * @enum {string}
             */
            semantic_type: "id" | "numeric" | "categorical" | "binary" | "datetime" | "text";
        };
        /** ResultsResponse */
        ResultsResponse: {
            predictions: components["schemas"]["PredictionsPage"];
            /** Results */
            results: {
                [key: string]: unknown;
            };
            /** Session Id */
            session_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "awaiting_confirmation" | "done" | "failed" | "interrupted";
        };
        /** RunStatusResponse */
        RunStatusResponse: {
            /** Session Id */
            session_id: string;
            /** Status */
            status: string;
        };
        /** SchemaProblems */
        SchemaProblems: {
            /** Message */
            message: string;
            /** Problems */
            problems: string[];
        };
        /**
         * SchemaProblemsOut
         * @description Body of a 422 from POST /confirm-schema when the schema does not fit the data.
         */
        SchemaProblemsOut: {
            detail: components["schemas"]["SchemaProblems"];
        };
        /** SchemaProposalOut */
        SchemaProposalOut: {
            /** Columns */
            columns: components["schemas"]["ProposedColumn"][];
            /** Id Columns */
            id_columns?: string[];
            /** Positive Label */
            positive_label?: string | null;
            /**
             * Reasoning
             * @default
             */
            reasoning: string;
            /** Revenue Column */
            revenue_column?: string | null;
            /**
             * Source
             * @enum {string}
             */
            source: "ai+rules" | "rules";
            /** Target Candidates */
            target_candidates?: string[];
            /** Target Column */
            target_column?: string | null;
            /** Time Column */
            time_column?: string | null;
        };
        /**
         * StreamEvents
         * @description Documentation only: the payload type of each SSE event name.
         */
        StreamEvents: {
            awaiting_confirmation: components["schemas"]["AwaitingConfirmationEvent"];
            done: components["schemas"]["DoneEvent"];
            error: components["schemas"]["ErrorEvent"];
            /** Heartbeat */
            heartbeat: {
                [key: string]: unknown;
            };
            node_finish: components["schemas"]["NodeFinishEvent"];
            node_start: components["schemas"]["NodeStartEvent"];
            /** Resumed */
            resumed: {
                [key: string]: unknown;
            };
        };
        /** UploadResponse */
        UploadResponse: {
            /**
             * Columns
             * @default []
             */
            columns: string[];
            /** Filename */
            filename: string;
            /** Rows */
            rows?: number | null;
            /** Session Id */
            session_id: string;
            /** Sheet Name */
            sheet_name?: string | null;
            /**
             * Sheets
             * @default []
             */
            sheets: string[];
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "choose_sheet";
            /**
             * Warnings
             * @default []
             */
            warnings: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    analyze_analyze__session_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStatusResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPErrorOut"];
                };
            };
            /** @description Gone */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_schema_confirm_schema__session_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmedSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStatusResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPErrorOut"];
                };
            };
            /** @description Gone */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPErrorOut"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchemaProblemsOut"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    results_results__session_id__get: {
        parameters: {
            query?: {
                page?: number;
                band?: ("High" | "Medium" | "Low") | null;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultsResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPErrorOut"];
                };
            };
            /** @description Gone */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    load_sample_sample_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPErrorOut"];
                };
            };
            /** @description Gone */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPErrorOut"];
                };
            };
            /** @description Content Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPErrorOut"];
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPErrorOut"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPErrorOut"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPErrorOut"];
                };
            };
        };
    };
    stream_stream__session_id__get: {
        parameters: {
            query?: {
                /** @description Resume after this event id. For clients that cannot send Last-Event-ID, such as a browser EventSource re-created after it closed. */
                after?: number | null;
            };
            header?: {
                "Last-Event-ID"?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server-sent events; StreamEvents maps each event name to its data payload. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamEvents"];
                    "text/event-stream": unknown;
                };
            };
            /** @description Gone */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPErrorOut"];
                };
            };
            /** @description Gone */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPErrorOut"];
                };
            };
            /** @description Content Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPErrorOut"];
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPErrorOut"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPErrorOut"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPErrorOut"];
                };
            };
        };
    };
    choose_sheet_upload__session_id__sheet_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_choose_sheet_upload__session_id__sheet_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPErrorOut"];
                };
            };
            /** @description Gone */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPErrorOut"];
                };
            };
            /** @description Content Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPErrorOut"];
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPErrorOut"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPErrorOut"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPErrorOut"];
                };
            };
        };
    };
}
